PROBLEM:
  PROBLEM_TYPE: "TuneDeepAR"
  DATAPATH: "data/vietnam_monthly.csv"

OPTIMIZER:
  OPTIMIZER_TYPE: "qEUBO"

BATCH_SIZE:
  EVAL_BATCH_SIZE: 2
  DM_BATCH_SIZE: 1

BUDGET:
  EVAL_BUDGET: 10
  DM_BUDGET: 10
